[workspace]
members = ["verifier", "examples/dob/dob-program", "examples/dob/dob-script","examples/proof-of-residence/program","examples/proof-of-residence/script"]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "1"
sp1-verifier = "6.1.0"
sp1-sdk = { version = "6.1.0", features = ["network"] }
sp1-zkvm = "6.1.0"
sp1-build = "6.1.0"
